let schedule = [
	{
		day: '1',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '2',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '5',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '6',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '7',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
		{
		day: '8',
		week: '목 THU',
		category: 'Teenager',
		title: 'Gugak Class for Youth',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: 'Yeongnam region elementary school students (3~6 grade), middle school students',
		inTit2: '-',
		inTit3: '3,000won per person',
		link: '0302.html'
	},
	{
		day: '8',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '9',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '12',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '13',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '14',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '15',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '16',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '19',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '20',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '21',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '22',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '23',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '28',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Talk with Masters',
		imgSrc: '../../asset/images/education/thumb/0203.jpg',
		inTit1: 'Busan local resident',
		inTit2: 'Gugak Specialists',
		inTit3: 'Free',
		link: '0203.html'
	},
		{
		day: '29',
		week: '목 THU',
		category: 'Teenager',
		title: 'Gugak Class for Youth',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: 'Yeongnam region elementary school students (3~6 grade), middle school students',
		inTit2: '-',
		inTit3: '3,000won per person',
		link: '0302.html'
	},
];