let schedule = [
	{
		day: '3',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum A gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '4',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori pansori minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '5',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum B gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '6',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori haegeum A minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '7',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">pansori haegeum B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '10',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum A gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '11',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori pansori minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '12',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum B gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '13',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori haegeum A minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '14',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">pansori haegeum B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '17',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum A gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '17',
		week: '월 MON',
		category: 'Educational expert',
		title: 'Gugak Class for Pre-Teachers',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: 'Students in Busan, Jinju, Daegu University of Education',
		inTit2: 'Busan National Gugak Center musicians, Invited instructors',
		inTit3: 'Free',
		link: '0102.html'
	},
	{
		day: '18',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori pansori minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '18',
		week: '화 TUE',
		category: 'Educational expert',
		title: 'Gugak Class for Pre-Teachers',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: 'Students in Busan, Jinju, Daegu University of Education',
		inTit2: 'Busan National Gugak Center musicians, Invited instructors',
		inTit3: 'Free',
		link: '0102.html'
	},
	{
		day: '19',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum B gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '19',
		week: '수 WED',
		category: 'Educational expert',
		title: 'Gugak Class for Pre-Teachers',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: 'Students in Busan, Jinju, Daegu University of Education',
		inTit2: 'Busan National Gugak Center musicians, Invited instructors',
		inTit3: 'Free',
		link: '0102.html'
	},
	{
		day: '20',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori haegeum A minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '20',
		week: '목 THU',
		category: 'Educational expert',
		title: 'Gugak Class for Pre-Teachers',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: 'Students in Busan, Jinju, Daegu University of Education',
		inTit2: 'Busan National Gugak Center musicians, Invited instructors',
		inTit3: 'Free',
		link: '0102.html'
	},
	{
		day: '21',
		week: '금 FRI',
        category: 'Teenager',
		title: 'Gugak Class for Youth',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: 'Yeongnam region elementary school students (3~6 grade), middle school students',
		inTit2: '-',
		inTit3: '3,000won per person',
		link: '0302.html'
	},
	{
		day: '21',
		week: '금 FRI',
		category: 'Educational expert',
		title: 'Gugak Class for Pre-Teachers',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: 'Students in Busan, Jinju, Daegu University of Education',
		inTit2: 'Busan National Gugak Center musicians, Invited instructors',
		inTit3: 'Free',
		link: '0102.html'
	},
	{
		day: '24',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum A gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '25',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori pansori minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '26',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">Drumming(buk&middot;janggu) haegeum B gayageum</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '27',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">samulnori haegeum A minyo</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '28',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School <span style="font-size:80%;">pansori haegeum B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
];