let schedule = [
	{
		day: '1',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '2',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '3',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '4',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '5',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '8',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '9',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '10',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '11',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '12',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '15',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '16',
		week: '화 TUE',
		category: 'Ordinary person',
		title: '2023 the First Half Saturday Lecture, Story Festival <Deom Deom Deom(More More Better)> ',
		imgSrc: '../../asset/images/education/thumb/0205.jpg',
		inTit1: 'Open to All',
		inTit2: '-',
		inTit3: 'Free',
		link: '0205.html'
	},
	{
		day: '17',
		week: '수 WED',
		category: 'Ordinary person',
		title: '2023 the First Half Saturday Lecture, Story Festival <Deom Deom Deom(More More Better)> ',
		imgSrc: '../../asset/images/education/thumb/0205.jpg',
		inTit1: 'Open to All',
		inTit2: '-',
		inTit3: 'Free',
		link: '0205.html'
	},
	{
		day: '18',
		week: '목 THU',
		category: 'Ordinary person',
		title: '2023 the First Half Saturday Lecture, Story Festival <Deom Deom Deom(More More Better)> ',
		imgSrc: '../../asset/images/education/thumb/0205.jpg',
		inTit1: 'Open to All',
		inTit2: '-',
		inTit3: 'Free',
		link: '0205.html'
	},
	{
		day: '19',
		week: '금 FRI',
		category: 'Ordinary person',
		title: '2023 the First Half Saturday Lecture, Story Festival <Deom Deom Deom(More More Better)> ',
		imgSrc: '../../asset/images/education/thumb/0205.jpg',
		inTit1: 'Open to All',
		inTit2: '-',
		inTit3: 'Free',
		link: '0205.html'
	},
	{
		day: '22',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '23',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '24',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '25',
		week: '금 FRI',
		category: 'Teenager',
		title: 'Gugak Class for Youth',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: 'Yeongnam region elementary school students (3~6 grade), middle school students',
		inTit2: '-',
		inTit3: '3,000won per person',
		link: '0302.html'
	},
	{
		day: '25',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '26',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '29',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '30',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '31',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
];