let schedule = [
	{
		day: '1',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '2',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '3',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">판소리 해금B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '4',
		week: '토 SAT',
		category: '일반인',
		title: '영남 춤 교실',
		imgSrc: '../../asset/images/education/thumb/0202.jpg',
		inTit1: '부산 지역 주민',
		inTit2: '외부 강사(문화재 보유자, 이수자)',
		inTit3: '100,000원',
		link: '0202.html'
	},
	{
		day: '4',
		week: '토 SAT',
		category: '외국인',
		title: '외국인 국악교실',
		imgSrc: '../../asset/images/education/thumb/0402.jpg',
		inTit1: '외국인',
		inTit2: '국립부산국악원 연주단, 외부 강사',
		inTit3: '무료',
		link: '0402.html'
	},
	{
		day: '4',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 국악연주단, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
	{
		day: '6',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금A 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '7',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 판소리 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '8',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '9',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '10',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">판소리 해금B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '11',
		week: '토 SAT',
		category: '일반인',
		title: '영남 춤 교실',
		imgSrc: '../../asset/images/education/thumb/0202.jpg',
		inTit1: '부산 지역 주민',
		inTit2: '외부 강사(문화재 보유자, 이수자)',
		inTit3: '100,000원',
		link: '0202.html'
	},
	{
		day: '11',
		week: '토 SAT',
		category: '외국인',
		title: '외국인 국악교실',
		imgSrc: '../../asset/images/education/thumb/0402.jpg',
		inTit1: '외국인',
		inTit2: '국립부산국악원 연주단, 외부 강사',
		inTit3: '무료',
		link: '0402.html'
	},
	{
		day: '11',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 국악연주단, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
	{
		day: '13',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금A 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '14',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 판소리 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '15',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '16',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '17',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">판소리 해금B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '18',
		week: '토 SAT',
		category: '일반인',
		title: '영남 춤 교실',
		imgSrc: '../../asset/images/education/thumb/0202.jpg',
		inTit1: '부산 지역 주민',
		inTit2: '외부 강사(문화재 보유자, 이수자)',
		inTit3: '100,000원',
		link: '0202.html'
	},
	{
		day: '18',
		week: '토 SAT',
		category: '외국인',
		title: '외국인 국악교실',
		imgSrc: '../../asset/images/education/thumb/0402.jpg',
		inTit1: '외국인',
		inTit2: '국립부산국악원 연주단, 외부 강사',
		inTit3: '무료',
		link: '0402.html'
	},
	{
		day: '18',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 국악연주단, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
/*	{
		day: '20',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금A 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '21',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 판소리 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '22',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '23',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '24',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">판소리 해금B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},*/
	{
		day: '25',
		week: '토 SAT',
		category: '일반인',
		title: '영남 춤 교실',
		imgSrc: '../../asset/images/education/thumb/0202.jpg',
		inTit1: '부산 지역 주민',
		inTit2: '외부 강사(문화재 보유자, 이수자)',
		inTit3: '100,000원',
		link: '0202.html'
	},
	{
		day: '25',
		week: '토 SAT',
		category: '외국인',
		title: '외국인 국악교실',
		imgSrc: '../../asset/images/education/thumb/0402.jpg',
		inTit1: '외국인',
		inTit2: '국립부산국악원 연주단, 외부 강사',
		inTit3: '무료',
		link: '0402.html'
	},
	{
		day: '25',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 국악연주단, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
];