let schedule = [
	{
		day: '1',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '2',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '5',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '6',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '7',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
		{
		day: '8',
		week: '목 THU',
		category: '청소년',
		title: '청소년 국악탐방',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: '영남지역 소재 초등학생(3~6학년), 중학생',
		inTit2: '-',
		inTit3: '1인 3천원',
		link: '0302.html'
	},
	{
		day: '8',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '9',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '12',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '13',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '14',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '15',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '16',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '19',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '20',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '21',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '22',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '23',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '28',
		week: '수 WED',
		category: '일반인',
		title: '명인에게 듣는 우리 국악',
		imgSrc: '../../asset/images/education/thumb/0203.jpg',
		inTit1: '부산 지역 주민',
		inTit2: '유명 국악인',
		inTit3: '무료',
		link: '0203.html'
	},
		{
		day: '29',
		week: '목 THU',
		category: '청소년',
		title: '청소년 국악탐방',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: '영남지역 소재 초등학생(3~6학년), 중학생',
		inTit2: '-',
		inTit3: '1인 3천원',
		link: '0302.html'
	},
];