let schedule = [
	{
		day: '3',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금A 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '4',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 판소리 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '5',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '6',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '7',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">판소리 해금B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '10',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금A 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '11',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 판소리 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '12',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '13',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '14',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">판소리 해금B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '17',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금A 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '17',
		week: '월 MON',
		category: '교육전문가',
		title: '예비교사 국악강좌',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: '부산, 진주, 대구 교대 재학생',
		inTit2: '국립부산국악원 직단원, 외부 강사',
		inTit3: '무료',
		link: '0102.html'
	},
	{
		day: '18',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 판소리 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '18',
		week: '화 TUE',
		category: '교육전문가',
		title: '예비교사 국악강좌',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: '부산, 진주, 대구 교대 재학생',
		inTit2: '국립부산국악원 직단원, 외부 강사',
		inTit3: '무료',
		link: '0102.html'
	},
	{
		day: '19',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '19',
		week: '수 WED',
		category: '교육전문가',
		title: '예비교사 국악강좌',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: '부산, 진주, 대구 교대 재학생',
		inTit2: '국립부산국악원 직단원, 외부 강사',
		inTit3: '무료',
		link: '0102.html'
	},
	{
		day: '20',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '20',
		week: '목 THU',
		category: '교육전문가',
		title: '예비교사 국악강좌',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: '부산, 진주, 대구 교대 재학생',
		inTit2: '국립부산국악원 직단원, 외부 강사',
		inTit3: '무료',
		link: '0102.html'
	},
	{
		day: '21',
		week: '금 FRI',
		category: '청소년',
		title: '청소년 국악탐방',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: '영남지역 소재 초등학생(3~6학년), 중학생',
		inTit2: '-',
		inTit3: '1인 3,000원',
		link: '0302.html'
	},
	{
		day: '21',
		week: '금 FRI',
		category: '교육전문가',
		title: '예비교사 국악강좌',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: '부산, 진주, 대구 교대 재학생',
		inTit2: '국립부산국악원 직단원, 외부 강사',
		inTit3: '무료',
		link: '0102.html'
	},
	{
		day: '24',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금A 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '25',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 판소리 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '26',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">고법(북&middot;장구) 해금B 가야금</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '27',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">사물놀이 해금A 민요</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '28',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교 <span style="font-size:80%;">판소리 해금B</span>',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
];