let schedule = [
	{
		day: '2',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '3',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '4',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '5',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '5',
		week: '목 THU',
		category: '청소년',
		title: '청소년 국악탐방',
		imgSrc: '../../asset/images/education/thumb/0302.jpg',
		inTit1: '영남지역 소재 초등학생(3~6학년), 중학생',
		inTit2: '-',
		inTit3: '1인 3천원',
		link: '0302.html'
	},
	{
		day: '6',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '7',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 연주단원, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
	{
		day: '9',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '10',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '11',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '12',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '13',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '14',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 연주단원, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
	{
		day: '16',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '17',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '18',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '19',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '20',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '21',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 연주단원, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
	{
		day: '23',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '24',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '25',
		week: '수 WED',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '26',
		week: '목 THU',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '27',
		week: '금 FRI',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '28',
		week: '토 SAT',
		category: '청소년',
		title: '어린이 연희단',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: '부산지역 초등학교 3~6학년(60명)',
		inTit2: '국립부산국악원 연주단원, 외부 강사',
		inTit3: '100,000원',
		link: '0303.html'
	},
	{
		day: '30',
		week: '월 MON',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
	{
		day: '31',
		week: '화 TUE',
		category: '일반인',
		title: '국악문화학교',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: '일반인(성인)',
		inTit2: '외부 강사',
		inTit3: '150,000원',
		link: '0201.html'
	},
];