let schedule = [
	{
		day: '1',
		week: '금 FRI',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '2',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '3',
		week: '일 SUN',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '8',
		week: '금 FRI',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '9',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '10',
		week: '일 SUN',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '15',
		week: '금 FRI',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '16',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '17',
		week: '일 SUN',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '22',
		week: '금 FRI',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '23',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '24',
		week: '일 SUN',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '29',
		week: '금 FRI',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '30',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '31',
		week: '일 SUN',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
];