let schedule = [
	{
		day: '1',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '2',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '3',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '4',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '6',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '7',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '8',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '9',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '10',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '11',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '13',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '14',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '15',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '16',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '17',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '17',
		week: '금 FRI',
		category: 'Educational expert',
		title: 'Gugak Class for Pre-Teachers',
		imgSrc: '../../asset/images/education/thumb/0102.jpg',
		inTit1: 'Students in Busan, Jinju, Daegu University of Education',
		inTit2: 'Busan National Gugak Center musicians, Invited instructors',
		inTit3: 'Free',
		link: '0102.html'
	},
	{
		day: '18',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '20',
		week: '월 MON',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '21',
		week: '화 TUE',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '22',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '23',
		week: '목 THU',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '24',
		week: '금 FRI',
		category: 'Ordinary person',
		title: 'Gugak Culture School',
		imgSrc: '../../asset/images/education/thumb/0201.jpg',
		inTit1: 'Adults',
		inTit2: 'Invited teachers',
		inTit3: '150,000won',
		link: '0201.html'
	},
	{
		day: '25',
		week: '토 SAT',
		category: 'Teenager',
		title: 'Children Folk Music Group',
		imgSrc: '../../asset/images/education/thumb/0303.jpg',
		inTit1: ' Busan Elementary schools 3~6 grade (60 students)',
		inTit2: 'Busan National Gugak Center Musicians, Invited instructors',
		inTit3: '100,000won',
		link: '0303.html'
	},
	{
		day: '29',
		week: '수 WED',
		category: 'Ordinary person',
		title: 'Talk with Masters',
		imgSrc: '../../asset/images/education/thumb/0203.jpg',
		inTit1: 'Busan local resident',
		inTit2: 'Gugak Specialists',
		inTit3: 'Free',
		link: '0203.html'
	},
];